JOWOMO/project-c

.github/workflows/rds.yml
.gitignore
backend/api/pgsql/db-create.pgsql
backend/api/pgsql/schema.pgsql
backend/api/serverless.yml
backend/rds/.gitignore
backend/rds/package-lock.json
backend/rds/package.json
backend/rds/serverless.yml

- RDS package
- RDS GitHub workflow

RDS deployment

---

frontend/apollo/graphql.d.ts
frontend/apollo/schema.ts
frontend/pages/register/company.vue

- Add schema validation to register company page

Add schema validation to register company page

---

.github/workflows/backend.yml
.github/workflows/frontend.yml
.github/workflows/rds.yml
backend/api/btb/api/__init__.py
frontend/middleware/authenticated.js
frontend/middleware/loaduser.js
frontend/nuxt.config.js
frontend/package.json
frontend/store/auth.js

Deployment issues

---

backend/api/btb/api/auth.py
backend/api/btb/api/schema/mutations/updateuser.py
backend/api/btb/api/schema/resolvers/me.py

- Identify user from claims
- New user not beeing inserted

User creation

---

frontend/layouts/error.vue
frontend/pages/dashboard.vue

added typescript to dashboard

---

frontend/apollo/queries/dashboard/demand.gql
frontend/apollo/queries/dashboard/supply.gql
frontend/apollo/schema.ts
frontend/components/match/company.vue
frontend/components/match/skill.vue
frontend/pages/dashboard/_flow/_id.vue

Highlight matching skills

---

backend/api/btb/templates/__main__.py
backend/api/btb/templates/code.py
backend/api/btb/templates/match.py
backend/api/btb/templates/render.py
backend/api/btb/templates/reset.py

Fix #83 html injection in mail templates

---

frontend/content/faq.md

Update spelling of JOWOMO in FAQ

---

backend/api/btb/api/schema/resolvers/team_names.py
backend/api/pgsql/31 real-data.pgsql
frontend/components/forms/validations.vue
frontend/components/team/index.vue
frontend/pages/register/_flow/team.vue

Frontend fixes part 2

---

frontend/assets/form.scss

Remove focus from input labels

---

frontend/components/decorator.ts
frontend/components/match/company.vue
frontend/content/about.md
frontend/content/faq.md
frontend/lang/de.js
frontend/nuxt.config.js
frontend/pages/connect/request/_.vue
frontend/pages/connect/response/_id.vue
frontend/pages/dashboard/company/_flow/_id.vue
frontend/pages/dashboard/match/_flow/_id.vue
frontend/pages/index.vue
frontend/pages/info/_.vue
frontend/pages/info/process.vue
frontend/pages/login/index.vue
frontend/pages/register.vue
frontend/pages/register/_flow/company.vue
frontend/pages/register/_flow/index.vue
frontend/pages/register/_flow/team.vue
frontend/pages/register/_flow/validate.vue
frontend/pages/welcome/_flow.vue
frontend/store/register.ts
frontend/tsconfig.json

- fixes #156
- fixes #153
- resolves #29
- fixes #137
- fixes #145 
- fixes #133

Content bugfixes

---

frontend/components/filter.vue
frontend/lang/de.js
frontend/pages/dashboard.vue
frontend/pages/dashboard/company.vue
frontend/pages/dashboard/index.vue
frontend/pages/dashboard/match.vue
frontend/pages/dashboard/match/_flow/_id.vue
frontend/pages/register/_flow/company.vue
frontend/pages/register/_flow/team.vue
frontend/pages/register/_flow/validate.vue
frontend/store/auth.ts
frontend/store/match.ts

Make team changes globally available

---

README.md
backend/api/README.md
frontend/readme.md

add readme

---

frontend/components/faq.vue

Fix FAQ toggle

---

frontend/components/forms/checkbox.vue
frontend/content/faq.md
frontend/pages/register/_flow/index.vue

includes https://github.com/JOWOMO/project-c/pull/199
resolves #196

Add checkbox to prevent temping agency signup

---

frontend/content/faq.md

More specific legal information plus additional question reg checklists for implementation after alignment with law firm

Update FAQ legal part after alignment with law firm

---

backend/api/btb/templates/code.py
backend/api/btb/templates/raw/code.html

Usability email code

---

frontend/package-lock.json
frontend/package.json

New fmdl release

---

frontend/content/faq.md

Additional questions plus edits in existing questions to supply additional information that were missing to some users from testbird

FAQ update after testbird feedback

---

frontend/components/forms/validations.vue

fixed small typo in validation

---

backend/api/btb/templates/code.py
backend/api/btb/templates/raw/code.html

Fix code in mail subject

---

backend/api/btb/api/constants.py
backend/api/btb/api/schema/mutations/createsupportrequest.py
backend/api/btb/api/schema/mutations/updatecompany.py
backend/api/btb/api/schema/mutations/updatedemand.py
backend/api/btb/api/schema/mutations/updatesupply.py
backend/api/btb/api/schema/mutations/updateuser.py
backend/api/btb/api/schema/types/util.py
frontend/components/auth/new.vue
frontend/components/forms/validations.vue
frontend/components/team/index.vue
frontend/constants/inputLengths.ts
frontend/lang/de.js
frontend/pages/register/_flow/company.vue
frontend/pages/register/_flow/index.vue
frontend/plugins/swal.ts

Add input length validation
